version: '3'
services:
    service_mongo:
      image: mongo:latest
      volumes:
        - ../db_data:/data/db
      ports:
        - 27017:27017
      logging:
        driver: none
    service_web:
      image: service_web
      build: .
      environment:
        - MONGO_IP=service_mongo
      ports:
        - 80:8080
      volumes:
        - ./:/root/
